### PR TITLE
[WIP] Delay slot filler framework

### LINKED ISSUE #728: Support architectural delay slots
Some architectures make use of branch delay slots, such as MIPS and SPARC; some even more exotic ones have load delay slots as well. Often enough there are also instructions with results only usable after certain number of cycles.

I'm trying to port Cranelift to MIPS64. I glanced over the codebase and found no support for filling the delay slots; I had to emit NOPs after every branch in the meantime.

So what's the current plan regarding this? A roadmap or implementation guide would be great!

### PR DESCRIPTION
**Pull request by xen0n**
Ripped out from the ongoing MIPS port for earlier review.

Some outstanding questions:

* [ ] How to tag instructions moved into delay slots as such, for verifier use?
* [ ] Should the `has_delay_slot` flag be moved into encinfo realm? Seems a little more work to do, but I'm willing to because delay slots are inherently ISA-specific.

Also some comments are not adjusted after copy-pasting... will fix these afterwards.

Closes #728.

### CODE REVIEW

**Comment by bnjbvr** [comment]
Hi! Sorry for not getting back to you earlier. We've discussed this yesterday in an internal meeting and came to the conclusion that each target would get its own target-specific peephole optimizer pass, very late in the pipeline, and that delay slot filling would happen there for MIPS.

This code was operating on the Python meta code, which has been migrated to Rust in the meanwhile, so it requires to be rebased. I wonder if putting the `has_delay_slot` property on the instruction makes sense (target-independent), or if it could be a property of the encoding (which is target specific).

**Comment by bnjbvr** [comment]
@xen0n ping? (see previous comment)

**Comment by xen0n** [comment]
@bnjbvr 

Hi, sorry for the delay. My research focus has since shifted mid-2019 and presently I don't have enough time to rework this on top of the current codebase, unfortunately.

As for whether the `has_delay_slot` property is target-independent or not, definitely it is encoding-specific; for example, MIPS R6 branches don't have delay slots while their pre-R6 counterparts do. So even treating all branch insns of a target as having the same delay slot property won't work.

**Comment by eqrion** [comment]
> @bnjbvr
> 
> Hi, sorry for the delay. My research focus has since shifted mid-2019 and presently I don't have enough time to rework this on top of the current codebase, unfortunately.
> 

That's not a problem, feel free to open a new PR if you ever take another look at this.

**Pull request closed without merging**
