### PR TITLE
Bump version to 0.50.0

### PR DESCRIPTION
**Pull request by abrown**
@sunfishcode, I think this commit didn't get a PR the last time `publish-all.sh` was run.

### CODE REVIEW

**Comment by abrown** [comment]
But, thinking about how this will affect Git history: crates.io has cranelift `0.50` crates already that are several commits behind `master` so if we merge this the Git history will not match the crates.io history. Another option is just to publish a `0.50.1` or something.

**Comment by bnjbvr** [comment]
We'll probably want to publish a 0.51.0 with an accompanying pull request.

**Comment by abrown** [comment]
Sounds good; I'm closing this.

**Comment by sunfishcode** [comment]
I've now published a 0.51, with an accompanying pull request, so hopefully everything is sorted out here now.

**Pull request closed without merging**
