### PR TITLE
Implement bitmask for SecondaryMap serialization

### PR DESCRIPTION
**Pull request by mrowqa**
Small improvement I was supposed to implement earlier. Might help https://github.com/dtolnay/watt/issues/2.

r? @sunfishcode

### CODE REVIEW

**Comment by bnjbvr** [comment]
Hey @mrowqa, can you give some context around this change: why is it useful, what does it change? (if it becomes lengthy, please open an issue!)

Is this covered by tests, and if not can you add some, please? Thanks!

**Comment by mrowqa** [comment]
The original reason was [cache system in Wasmtime](https://github.com/bytecodealliance/wasmtime/blob/e5af0ae3debf5e9aa49caabed32738dbcd07b690/crates/environ/src/cache.rs). It uses serde for serialization of compilation cache which consists of `SecondaryMap`s (among others). At the time of implementing the cache system, I had implemented simpler `SecondaryMap` serializer (current code) that uses whole byte for a bit flag (presence of an object at a given index) and this PR changes the serializer to pack these bit flags compactly. After implementing the simpler serialization, I had added compression to the cache system, so using whole bytes for single bit information shouldn't affect too much the size of the final cache that lands on user disk. I haven't measured the difference in performance and peak memory usage (intermediate step - after decompression, before deserialization) that this PR introduces.

The change is tested by Wasmtime cache system tests.

CC @sunfishcode

**Comment by alexcrichton** [comment]
Thanks for the PR again, and as a procedural note the Cranelift repository [has now merged](https://github.com/bytecodealliance/cranelift/issues/1408) into the [wasmtime repository](https://github.com/bytecodealliance/wasmtime/tree/master/cranelift).

PRs are no longer landing in this repository, and unfortunately there's no "one button" solution to move a PR to the wasmtime repository. A [script has been prepared](https://gist.github.com/alexcrichton/8cb3f4ef7c25317ba6824ee31e3e53aa), however, to assist you in transferring this PR to the wasmtime repo. Feel free to reach out on Zulip with any questions!

**Comment by tschneidereit** [comment]
We'll archive this repository in favor of the Wasmtime repository — see Alex's comment about the merge above. I'm closing this PR now in order to have an explanation in a comment before archiving the repo auto-closes all PRs.

**Pull request closed without merging**
