### PR TITLE
Derive Ord for all entities

### PR DESCRIPTION
**Pull request by bjorn3**
- [x] This has been discussed in issue #..., or if not, please tell us why
  here. Small change
- [x] A short description of what this does, why it is needed; if the
  description becomes long, the matter should probably be discussed in an issue
  first. This is necessary to store them in `BTreeMap` and `BTreeSet`.
- [x] This PR contains test cases, if meaningful. N/A
- [ ] A reviewer from the core maintainer team has been assigned for this PR.
  If you don't know who could review this, please indicate so and/or ping
  `bnjbvr`. The list of suggested reviewers on the right can help you.

### CODE REVIEW

**Comment by sstangl** [comment]
What's the use case for this? The internal number assigned to an entity is basically arbitrary.

**Comment by bjorn3** [comment]
I want to use a `BTreeMap` instead of `HashMap` for determinism. `Value` and `Inst` already derive `Ord`.

**Comment by bnjbvr** [comment]
ping @bjorn3, can you address Sean's comment, rebase, and make sure your tests pass, please? Thanks!

**Comment by bjorn3** [comment]
Rebased and addressed comment.

**Comment by bnjbvr** [comment]
Thank you!

**Pull request merged**
