### PR TITLE
Mass rename Ebb and relatives to Block

### PR DESCRIPTION
**Pull request by eqrion**
Another component of #1303. From experience with mass-renames across Gecko, I've split the patches to be fine grained and marked whether the patch is automatic (i.e. find-replace) or manual. This helps in rebasing and reviewing, although the changes are quite large so those will still be challenging.

I'm opening this as a draft pull-request so that interested parties have a chance to look at this. It should be relatively good to go once consensus on naming is reached.

### CODE REVIEW

**Comment by abrown** [comment]
@eqrion, this makes sense to me. Why don't we mark this ready for review?

**Comment by eqrion** [comment]
> @eqrion, this makes sense to me. Why don't we mark this ready for review?

I just realized that I had forgotten to clean up the ordering of the commits. I'll do that first and then mark this ready for review.

**Comment by abrown** [comment]
I think we will want to "squash and merge" this PR to make it atomic?

**Comment by eqrion** [comment]
Yeah, this is probably ready for review. I see there are now conflicts. I think the best way forward is to review this as-is, and then when we're ready to merge I can rebase by re-creating the automatic rename commits.

**Pull request merged**
